services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: wedding-app
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - wedding

    db:
        image: postgres:15
        container_name: wedding-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - wedding

    redis:
        image: redis:alpine
        container_name: wedding-redis
        ports:
            -   "6380:6379"
        volumes:
            -   redisdata:/data
        restart: unless-stopped
        networks:
            - wedding

    nginx:
        image: nginx:alpine
        container_name: wedding-nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - wedding

volumes:
    pgdata:
    redisdata:

networks:
    wedding:
